// v6.9.1950
(function(y,p,I,z,D,v,ca,n){function t(a,c,b){return function(){a(c,b)}}function E(a){return"object"==typeof a}function ua(){for(var a=32,c="";a--;)c+=(0|16*Math.random()).toString(16);return c}function F(a,c,b,d,f){(f=a.addEventListener)?f.call(a,c,b,!1):a.attachEvent(d||"on"+c,b)}function da(){return I&&"preview"==I.loadPurpose}function J(a,c){for(var b in a)a.hasOwnProperty(b)&&a[b]!==n&&c(a[b],b)}function K(a,c){var b=[];J(a,function(d,f){var g=b.push,e=ca(f)+"=";if(c){var h=(typeof d).charAt(0);
h=("[object Array]"==W.call(d)?"a":"[object Date]"==W.call(d)?"d":h)+("[object Date]"==W.call(d)?+d:E(d)&&d?K(d,c):d)}else h=d;g.call(b,e+ca(h))});return b.join("&")}function L(a,c){if(!a)throw Error(c);}function va(a){S[ea]=a;return ea++}function G(a,c,b,d,f){c?a(T(c),b,d,f):J(r,function(g){a(g,b,d,f)})}function fa(a){a=new v(a);return"expires="+a.toGMTString()+";"}function U(a,c){var b="path=/;",d=a.g(6);d&&(b+="domain="+d+";");"https:"==location.protocol&&(b+="secure");return{u:function(f,g){a.g(1,
!0)&&(p.cookie=f+"="+g+";"+fa(+new v+(c?6E10:6E4))+b)},B:function(f){if(a.g(1,!0))return(p.cookie.match("(^|;)\\s*"+f+"=([^;]*)")||[])[2]||n},X:function(f){p.cookie=f+"=;"+fa(0)+b}}}function ha(a){a.m&&(a.m=!1,a.A=new v-a.G+(a.A||0))}function ia(a){D(a.ca);a.ca=z(t(ha,a),15E3);a.m||(a.m=!0,a.G=new v)}function wa(a){var c=a.A,b=new v;a.m&&(c+=b-a.G,a.G=b);a.A=0;return c}function xa(a){var c=t(ia,a);F(p,"mousemove",c);F(p,"keydown",c);F(y,"scroll",c);F(p,"focus",c,"focusin");F(p,"blur",t(ha,a),"focusout")}
function ja(a,c){var b=p.getElementsByTagName("head")[0],d=p.createElement("script"),f=+new v;d.onerror=function(){100>+new v-f&&c&&c()};d.src=a;b.appendChild(d);return function(){d&&b.removeChild(d);d=null}}function M(a,c,b,d,f,g){var e=t;if(-1===ya.indexOf(a.h.slice(4))){var h=z(function(){e();X=(X+1)%Y.length;b.et&&(b.et=0);b.rt=1;--f&&M(a,c,b,d,f,g)},5E3),l=H(a);b.cb=va(function(k,m,A){e();D(h);d(k,m,A)});b.a=a.h;b.au=l.L;b.id=l.j;b.cid=l.D;b.tv="6.9.1950";l=c+"?"+K(b);e=ja("https://"+("chat"==
c?c:Y[X])+".gosquared.com/"+l,g)}}function V(a,c,b,d){if(a.i!==n)b||(b={}),b.i=a.i,b.e=c,b.et=wa(a),w&&(b.bc=1),M(a,"ping",b,function(e){d&&d();null!==e&&(D(a.o),a.o=z(t(V,a),[1E4,2E4][a.fa++]||27500+5E3*Math.random()))},5);else{var f=function(){g||(g=1,V(a,c,b,d))},g;a.S.push(f);z(f,5E3)}}function Z(a,c,b,d){L(c,"Event name is required");b&&b.call&&(d=b,b=n);if(b===""+b||b===+b)b={caption:b};c={gs_evt_name:c,d:K(b||{},!0)};V(a,"event",c,d)}function za(a,c,b,d){function f(k,m){m=m||(E(k)?k:{});E(k)||
(m.name=k);L(m.name,"No Name");h.push(m);return l}function g(k){for(var m=0;m<k.length;)f(k[m++]);return l}function e(){G(function(k){var m=U(k,1),A="gs_t_"+k.h,u=m.B(A)||0;m.u(A,+new v);Z(k,"_transaction",{id:c,pt:{ts:+u},i:h,d:b})},a)}!b&&E(c)&&(b=c,c=b.id);var h=[],l;d&&g(d);b&&b.track&&e();return l={id:c,addItem:f,addItems:g,track:e}}function Aa(a){var c=p.createElement("a");c.href=a||y.location.href;return c.href}function ka(a,c,b){c=Aa(c);a.g(7,!0)||(c=c.replace(/\?([^#]*)/,function(d,f){f=
f.split("&");for(var g=[],e=0;e<f.length;e++)/^utm_/.test(f[e])&&g.push(f[e]);return g.length?"?"+g.join("&"):""}));a.g(8)||(c=c.replace(/#.*$/,""));return{ea:c,da:b!==n?b:p.title,R:/^file:/.test(c)||/\/\/localhost[\/:]/.test(c+"/"),P:/fb_xd_(bust|fragment)/.test(c)}}function Ba(a){a=a.g(10,p.referrer);var c;!a||/^(chrome|about|file):/.test(a)||/^\[.*\]$/.test(a)?a="-":c=a.replace(/^.*?\/\//,"").indexOf(location.host);return{O:+(0<=c&&8>=c),ia:a}}function Ca(){var a=0,c=0;screen&&(a=screen.width,
c=screen.height);var b=(b=y.orientation)&&(b+360)%180;return{J:b?c:a,I:b?a:c,na:screen&&screen.colorDepth||"-",W:I.language||I.browserLanguage||"-",Y:p.characterSet||p.charSet||"-",ga:y.devicePixelRatio||1,pa:I.maxTouchPoints||0,ba:(new v).getTimezoneOffset()}}function N(a){function c(){var e=d.name;e&&(d.name=e.split(":_GS_:")[0])}var b;if(N[a])return N[a];var d=y.top;N[a]=b=function(){c();d.name=(d.name||"")+":_GS_:"+[a,b.j,b.H]};try{var f=d.name||"";if(-1!=f.indexOf(":_GS_:")){var g=f.split(":_GS_:")[1].split(",");
g[0]==a&&(b.j=g[1]||"",b.H=g[2]||"")}c()}catch(e){d={}}return b}function Da(a){if(a.i!==n){var c=U(a);a.g(1,!0)?c.u("gs_p_"+a.h,a.i):(c=N(a.h),c.H=a.i,c())}}function aa(a,c,b,d){c&&c.call&&(d=c,c=n);b&&b.call&&(d=b,b=n);b=ka(a,c,b);var f=Ba(a),g=a.i===n&&!f.O,e=a.K=H(a),h=Ca(),l=a.g(5);e.Z(1,g);D(a.o);a.A=0;a.m=!1;ia(a);if(!(!a.g(9)&&b.R||b.P||da()||h.J&&h.I&&10>h.J&&10>h.I)){var k={cs:h.Y,cd:h.na,la:h.W,sw:h.J,sh:h.I,dp:h.ga,tp:h.pa,pu:b.ea,pt:b.da||"-",ri:f.O,ru:f.ia,re:+e.ka,vi:e.F,pv:e.C,lv:e.aa,
un:a.g(3),pp:e.ha(),ec:l,aip:a.g(2)?1:n,tz:h.ba};a.l&&(k.cp=K(a.l,!0));a.ja||!1===a.g(15)||(k.rc=1,a.ja=!0);w&&(a.uid=e.j,k.bc=1);a.fa=0;var m;M(a,"pv",k,function(A,u){if(A!==n){a.i=A;D(a.o);a.o=z(t(V,a),5E3);for(var C;C=a.S.shift();)C();d&&d()}u&&!m&&la(a,u)},5,function(){k.rc&&!m&&(m=1,Ea(a))});a.i!==n?c!==n&&(a.i=n):(z(t(xa,a),500),F(y,"beforeunload",t(Da,a)))}}function Fa(a,c,b){!b&&E(c)&&(b=c,c=b.id,!c&&b.email&&(c="email:"+b.email));L(c,"ID or email required");"__n/v_"!==c&&a.s(13,c);b&&a.s(4,
b)}function x(a,c,b,d){if(a&&a.call)a();else if(/^GSN-.*-.$/.test(a))c!==""+c&&(b=c,c=0),ba(a,c,b||b===n);else if(S[a])S[a](c,b,d),delete S[a];else{var f=function(e,h,l){g?T(g).s(e,h,l):J(r,function(k){k.s(e,h,l)})};a=a.split(".");var g;1<a.length&&(g=a.shift());a=a[0];if(/transaction$/i.test(a))return za(g,c,b,d);if("get"==a)return b=ma[(c+"").toLowerCase()]||c,g?d=T(g).g(b):J(r,function(e){d=e.g(b)}),d;"set"==a?(a=(c+"").split("."),c=a.shift(),f(ma[c.toLowerCase()]||c,b,a.join("."))):"track"==a?
G(aa,g,c,b,d):"event"==a?G(Z,g,c,b,d):"cancel"==a?G(function(e){e.M()},g):"noCookies"==a?f(1,!1):"anonymizeIP"==a?f(2,!0):"tag"==a?f(3,c):"load"==a?c&&c():"auth"==a?f(14,c):"identify"==a?G(Fa,g,c,b,d):"alias"==a?f(13,c):"unidentify"==a?G(function(e){if(e.g(13)||O(["e",e.h]))e.s(13),H(e).ma(1)}):"props"==a||"properties"==a?f(4,c):"chat"==a&&O([c,b,d])}}function O(a){var c=x.c;c||(c=x.c=function(b){c.q.push(b)},c.q=[]);return c(a)}function la(a,c){O(c);var b=x.c;b.c||(b.c=[2,a.h,a.g(15),a.g(11),a.g(6)]);
var d="https://js.gs-chat.com/chat",f=(b=c[0])&&b.channel;f&&(d+="-"+f);d=(a.g(15)||{}).js||d+".js";na||(na=!0,ja(d+(b?"?"+b.v:"")))}function Ea(a){M(a,"chat",{},function(c){c&&(c[0]&&(c[0].notrack=1),la(a,c))})}function H(a){function c(q){g.u(d,e.j=q?"":[k,548*B.F+2019,379*B.C+4621,+new v].join(":"));a.s(11,q?0:k)}function b(q){u&&"-"!==u?(g.u(f,u+(C?"|"+C:"")),O(["i",a.h,u,C,q])):(g.u(f,""),O(["u",a.h,q]))}var d="gs_u_"+a.h,f="gs_v_"+a.h,g=U(a,1),e=N(a.h),h=(g.B(d)||e.j||"").split(/(?::|%3A)/),
l=!0,k=a.g(11,h[0])||(l=!1,ua()),m=((h[1]||2019)-2019)/548,A=((h[2]||4621)-4621)/379;h=(h[3]||0)/1E3;var u=a.g(13),C=a.g(14);var B={j:k,D:u,F:m,C:A,aa:~~h,ka:l,Z:function(q,Ga){B.C+=+q;B.F+=+Ga;c()},U:function(q){u=B.D=q;b(1)},ma:c,ha:function(){var q=g.B("gs_p_"+a.h)||e.H;g.X("gs_p_"+a.h);return a.i!==n?a.i:q},L:C,oa:function(q){L(/^[0-9a-f]{64}$/.test(q),"Invalid auth signature");C=B.L=q;b(1)}};b();return B}function oa(a){if(a.K){var c=ka(a);!a.g(9)&&c.R||c.P||da()||(c=K(a.l,!0))&&M(a,"prop",{cp:c},
t,5)}else z(function(){oa(a)},100)}function pa(a,c,b){var d=a.l=a.l||{};L(c||E(b),"Not an object");c?d[c]=b:d=a.l=b;!a.T&&a.K&&(a.T=z(function(){oa(a);a.T=0},5))}function qa(a){var c="gs_v_"+a,b=this,d=[];d[12]=b.h=a;b.s=function(g,e,h){4==g&&(pa(b,h,e),e&&!b.N&&(h=e.id,e=e.email,!h&&e&&(h="email:"+e),h&&(b.N=h,H(b).U(h))),e=b.l);13==g&&(pa(b,"id",e),e=(b.N=e)||"-",H(b).U(e));14==g&&H(b).oa(e);d[g]=e};b.g=function(g,e){function h(){var l=U(b,1).B(c);if(/\|[0-9a-f]{32,64}/.test(l)){l=l.split("|");
var k=l.pop();l=l.join("|")}return{V:k,D:l}}return g in d?d[g]:13===g?h().D||e:14===g?h().V||e:e};var f;b.$=function(){f=z(t(aa,b),20)};b.M=function(){D(b.o);D(f)};b.S=[]}function ba(a,c,b){if(!a)for(a in r)return r[a];if(r[c||a])return r[c||a];a=r[c||a]=new qa(a);b&&a.$();return a}function T(a){var c=r[a];if(c)return c;for(var b in r)if(r[b].h==a)return r[b]}function ra(a){return function(c,b,d){a(this,c,b,d)}}function Ha(){if(w){var a=qa.prototype;a.TrackView=ra(aa);a.TrackEvent=ra(Z);a.Cancel=
function(){this.M()};w.Tracker=ba;w.Cancel=t(x,"cancel");J(w,function(c,b){"acct"==b?(ba(c,"_default",!0),x(function(){function d(g){f[g.shift()].apply(f,g)}var f=w.DefaultTracker=T("_default");if(b=w.q)for(;c=b.shift();)d(c);w.q={push:d};(b=w.load)&&b(f)})):"load"!=b&&"q"!=b&&x("set",b,c)})}}var W=Object.prototype.toString,S={},ea=0,Y=["data","data2"],X=0|Math.random()*Y.length,ya=["448608-A","226025-N"],ma={usecookies:1,anonymizeip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,
trackhash:8,tracklocal:9,referrer:10,visitorid:13,visitor:4,clientid:11,auth:14,props:4,properties:4,chat:15},na,r={},w=y.GoSquared,P,Q=y._gs||(P=!0,function(){sa.push(arguments)}),sa=Q.q||[];if(!Q.v){var R=function(a){x.apply({},a)};y._gs=x;x.v="6.9.1950";for(Q.q={push:R};Q=sa.shift();)R(Q);Ha();if(P){P=p.getElementsByTagName("script");R=P.length;for(var ta;R--;)(ta=P[R].getAttribute("data-gs"))&&x(ta)}}})(window,document,navigator,setTimeout,clearTimeout,Date,encodeURIComponent);
